-- MySQL Script generated by MySQL Workbench
-- Sun Dec  3 01:49:28 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema aims
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema aims
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `aims` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_vietnamese_ci ;
USE `aims` ;

-- -----------------------------------------------------
-- Table `aims`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aims`.`role` (
  `id` INT NOT NULL,
  `roleName` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_vietnamese_ci;


-- -----------------------------------------------------
-- Table `aims`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aims`.`user` (
  `id` INT NOT NULL,
  `fullName` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `username` VARCHAR(255) NULL DEFAULT NULL,
  `role_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK84qlpfci484r1luck11eno6ec` (`role_id` ASC) VISIBLE,
  CONSTRAINT `FK84qlpfci484r1luck11eno6ec`
    FOREIGN KEY (`role_id`)
    REFERENCES `aims`.`role` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_vietnamese_ci;


-- -----------------------------------------------------
-- Table `aims`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aims`.`order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `delivered` BIT(1) NOT NULL,
  `shipping_fees` DOUBLE NULL DEFAULT NULL,
  `total` DOUBLE NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK54bcuqqji0ui86bdbc75thhld` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK54bcuqqji0ui86bdbc75thhld`
    FOREIGN KEY (`user_id`)
    REFERENCES `aims`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_vietnamese_ci;


-- -----------------------------------------------------
-- Table `aims`.`delivery_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aims`.`delivery_info` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `delivery_íntruction` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `phone` VARCHAR(255) NULL DEFAULT NULL,
  `province` VARCHAR(255) NULL DEFAULT NULL,
  `rush` BIT(1) NOT NULL,
  `order_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_743hn86wgilfhhq2axcx0datv` (`order_id` ASC) VISIBLE,
  CONSTRAINT `FKdifi3ynn2el0itoj6au3rya5r`
    FOREIGN KEY (`order_id`)
    REFERENCES `aims`.`order` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_vietnamese_ci;


-- -----------------------------------------------------
-- Table `aims`.`invoice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aims`.`invoice` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `total` DOUBLE NOT NULL,
  `order_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_fplnqqohyvdr3pw8aoq1a2d93` (`order_id` ASC) VISIBLE,
  CONSTRAINT `FKll5bj5n4vea21vxlye6cwjh33`
    FOREIGN KEY (`order_id`)
    REFERENCES `aims`.`order` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_vietnamese_ci;


-- -----------------------------------------------------
-- Table `aims`.`media`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aims`.`media` (
  `media_type` VARCHAR(31) NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `category` ENUM('BOOK', 'CD', 'DVD') NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `dimensions` VARCHAR(255) NULL DEFAULT NULL,
  `image_url` VARCHAR(255) NULL DEFAULT NULL,
  `price` DOUBLE NOT NULL,
  `quantity` INT NOT NULL,
  `receipt_date` DATE NULL DEFAULT NULL,
  `rushSupport` BIT(1) NOT NULL,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `value` VARCHAR(255) NULL DEFAULT NULL,
  `authors` VARCHAR(255) NULL DEFAULT NULL,
  `cover` VARCHAR(255) NULL DEFAULT NULL,
  `genre` VARCHAR(255) NULL DEFAULT NULL,
  `language` VARCHAR(255) NULL DEFAULT NULL,
  `pages` INT NULL DEFAULT NULL,
  `publication_date` DATE NULL DEFAULT NULL,
  `publisher` VARCHAR(255) NULL DEFAULT NULL,
  `artists` VARCHAR(255) NULL DEFAULT NULL,
  `record_label` VARCHAR(255) NULL DEFAULT NULL,
  `release_date` DATE NULL DEFAULT NULL,
  `tracklist` VARCHAR(255) NULL DEFAULT NULL,
  `director` VARCHAR(255) NULL DEFAULT NULL,
  `runtime` INT NULL DEFAULT NULL,
  `studio` VARCHAR(255) NULL DEFAULT NULL,
  `subtitle` VARCHAR(255) NULL DEFAULT NULL,
  `type` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_vietnamese_ci;


-- -----------------------------------------------------
-- Table `aims`.`order_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aims`.`order_item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `price` DOUBLE NOT NULL,
  `quantity` INT NOT NULL,
  `media_id` INT NULL DEFAULT NULL,
  `order_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKvhgtkiqtkj9t6cmknf7n3qm8` (`media_id` ASC) VISIBLE,
  INDEX `FKs234mi6jususbx4b37k44cipy` (`order_id` ASC) VISIBLE,
  CONSTRAINT `FKs234mi6jususbx4b37k44cipy`
    FOREIGN KEY (`order_id`)
    REFERENCES `aims`.`order` (`id`),
  CONSTRAINT `FKvhgtkiqtkj9t6cmknf7n3qm8`
    FOREIGN KEY (`media_id`)
    REFERENCES `aims`.`media` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_vietnamese_ci;


-- -----------------------------------------------------
-- Table `aims`.`payment_transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aims`.`payment_transaction` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` DATE NULL DEFAULT NULL,
  `invoice_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_ql9p64lgm6l9c6vvb9ir2s8ny` (`invoice_id` ASC) VISIBLE,
  CONSTRAINT `FK46c7192sqo7kt42bcx735nvqn`
    FOREIGN KEY (`invoice_id`)
    REFERENCES `aims`.`invoice` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_vietnamese_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
