-- MySQL Script generated by MySQL Workbench
-- Fri Nov  3 16:26:44 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Media`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Media` (
  `id` INT GENERATED ALWAYS AS () VIRTUAL,
  `category` VARCHAR(45) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `price` INT NOT NULL,
  `quantity` INT NOT NULL,
  `imageURL` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Book` (
  `genre` VARCHAR(45) NOT NULL,
  `authors` VARCHAR(45) NOT NULL,
  `publisher` VARCHAR(45) NOT NULL,
  `publicationDate` DATE NOT NULL,
  `pages` INT NULL,
  `cover` VARCHAR(45) NULL,
  `language` VARCHAR(45) NOT NULL,
  `mediaId` INT NOT NULL,
  PRIMARY KEY (`mediaId`),
  CONSTRAINT `fk_Book_Media1`
    FOREIGN KEY (`mediaId`)
    REFERENCES `mydb`.`Media` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CD` (
  `genre` VARCHAR(45) NOT NULL,
  `artists` VARCHAR(45) NOT NULL,
  `releaseDate` DATE NOT NULL,
  `tracklist` VARCHAR(45) NULL,
  `recordLabel` VARCHAR(45) NOT NULL,
  `mediaId` INT NOT NULL,
  PRIMARY KEY (`mediaId`),
  CONSTRAINT `fk_CD_Media`
    FOREIGN KEY (`mediaId`)
    REFERENCES `mydb`.`Media` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DVD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DVD` (
  `type` VARCHAR(45) NOT NULL,
  `genre` VARCHAR(45) NOT NULL,
  `releaseDate` DATE NOT NULL,
  `studio` VARCHAR(45) NOT NULL,
  `director` VARCHAR(45) NOT NULL,
  `language` VARCHAR(45) NOT NULL,
  `subtitles` VARCHAR(45) NOT NULL,
  `runtime` INT NOT NULL,
  `mediaId` INT NOT NULL,
  PRIMARY KEY (`mediaId`),
  CONSTRAINT `fk_DVD_Media1`
    FOREIGN KEY (`mediaId`)
    REFERENCES `mydb`.`Media` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Order` (
  `id` INT NOT NULL,
  `shippingFees` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DeliveryInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DeliveryInfo` (
  `id` INT GENERATED ALWAYS AS () VIRTUAL,
  `name` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `province` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `deliveryInstruction` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `orderId` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_DeliveryInfo_Order1_idx` (`orderId` ASC) VISIBLE,
  CONSTRAINT `fk_DeliveryInfo_Order1`
    FOREIGN KEY (`orderId`)
    REFERENCES `mydb`.`Order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RushDeliveryInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RushDeliveryInfo` (
  `pickupTime` DATETIME NOT NULL,
  `content` VARCHAR(45) NOT NULL,
  `deliveryInfoId` INT NOT NULL,
  PRIMARY KEY (`deliveryInfoId`),
  CONSTRAINT `fk_RushDeliveryInfo_DeliveryInfo1`
    FOREIGN KEY (`deliveryInfoId`)
    REFERENCES `mydb`.`DeliveryInfo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Invoice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Invoice` (
  `id` INT GENERATED ALWAYS AS () VIRTUAL,
  `total` VARCHAR(45) NOT NULL,
  `orderId` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Invoice_Order1_idx` (`orderId` ASC) VISIBLE,
  CONSTRAINT `fk_Invoice_Order1`
    FOREIGN KEY (`orderId`)
    REFERENCES `mydb`.`Order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Card` (
  `id` INT GENERATED ALWAYS AS () VIRTUAL,
  `owner` VARCHAR(45) NOT NULL,
  `expirationDate` DATE NOT NULL,
  `securityCode` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PaymentTransaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PaymentTransaction` (
  `id` INT GENERATED ALWAYS AS () VIRTUAL,
  `content` VARCHAR(45) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `cardId` INT NOT NULL,
  `invoiceId` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_PaymentTransaction_Card1_idx` (`cardId` ASC) VISIBLE,
  INDEX `fk_PaymentTransaction_Invoice1_idx` (`invoiceId` ASC) VISIBLE,
  CONSTRAINT `fk_PaymentTransaction_Card1`
    FOREIGN KEY (`cardId`)
    REFERENCES `mydb`.`Card` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PaymentTransaction_Invoice1`
    FOREIGN KEY (`invoiceId`)
    REFERENCES `mydb`.`Invoice` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OrderMedia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OrderMedia` (
  `quantity` INT NOT NULL,
  `price` INT NOT NULL,
  `mediaId` INT NOT NULL,
  `orderId` INT NOT NULL,
  PRIMARY KEY (`mediaId`, `orderId`),
  INDEX `fk_OrderMedia_Order1_idx` (`orderId` ASC) VISIBLE,
  CONSTRAINT `fk_OrderMedia_Media1`
    FOREIGN KEY (`mediaId`)
    REFERENCES `mydb`.`Media` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrderMedia_Order1`
    FOREIGN KEY (`orderId`)
    REFERENCES `mydb`.`Order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mydb` ;

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `mydb`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`view1`;
USE `mydb`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
